using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LeetCodeExample.Test
{
    /// <summary>
    //You are given two strings s and t.
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //Return the letter that was added to t.
    /// </summary>
    public class _00389_FindTheDifference
    {
        public char FindTheDifference(string s, string t)
        {
            int[] letters = new int[26];
            for (int i = 0; i < t.Length; i++)
            {
                letters[t[i] - 'a']++;
            }

            for (int i = 0; i < s.Length; i++)
            {
                letters[s[i] - 'a']--;
            }

            for (int i = 0; i < 26; i++)
            {
                if (letters[i] != 0)
                {
                    return (char)('a' + i);
                }
            }
            return ' ';
        }
    }
}